<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-07T20:54:55 IST" name="Default suite" finished-at="2023-09-07T20:54:56 IST" duration-ms="959">
    <groups>
    </groups>
    <test started-at="2023-09-07T20:54:55 IST" name="Default test" finished-at="2023-09-07T20:54:56 IST" duration-ms="959">
      <class name="DemoJenkins.DemoJenkins.extr">
        <test-method is-config="true" signature="startReport()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:55 IST" name="startReport" finished-at="2023-09-07T20:54:55 IST" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="t1()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:55 IST" name="t1" finished-at="2023-09-07T20:54:55 IST" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t1 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:55 IST" name="getResult" finished-at="2023-09-07T20:54:55 IST" duration-ms="9" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=t1 status=SUCCESS method=extr.t1()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method signature="t2()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:55 IST" name="t2" finished-at="2023-09-07T20:54:55 IST" duration-ms="2" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at DemoJenkins.DemoJenkins.extr.t2(extr.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t2 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:55 IST" name="getResult" finished-at="2023-09-07T20:54:56 IST" duration-ms="385" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=t2 status=FAILURE method=extr.t2()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method signature="t3()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:56 IST" name="t3" finished-at="2023-09-07T20:54:56 IST" duration-ms="1" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[The test has been skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: The test has been skipped
at DemoJenkins.DemoJenkins.extr.t3(extr.java:69)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t3 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:56 IST" name="getResult" finished-at="2023-09-07T20:54:56 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=t3 status=SKIP method=extr.t3()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method signature="t4()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:56 IST" name="t4" finished-at="2023-09-07T20:54:56 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- t4 -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:56 IST" name="getResult" finished-at="2023-09-07T20:54:56 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=t4 status=SUCCESS method=extr.t4()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:DemoJenkins.DemoJenkins.extr@58cbafc2]" started-at="2023-09-07T20:54:56 IST" name="tearDown" finished-at="2023-09-07T20:54:56 IST" duration-ms="301" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- DemoJenkins.DemoJenkins.extr -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
